spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clearsolutionsdb
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  registration:
    min-age: 18